alias zshhelp='display_help_menu'
alias help='display_help_menu'
alias record='cd /home/remcostoeten/projects/zsh-setup/utils/ && ./record-mp3'
alias voice='python /home/remcostoeten/projects/zsh-setup/scripts/voice-to-clipboard.py xxerec'
alias voicenl='python /home/remcostoeten/projects/zsh-setup/scripts/voice-to-clipboard.py rec -nl'
