alias vim='nvim'
alias code='code .'
alias cursor='cursor .'
alias brave='brave .'
alias chrome='google-chrome .'
alias firefox='firefox .'
alias cursorapp='cd ~/Applications'
alias cursor='cursorapp && ./cursor'