export APPS='cd ~/Applications/'
alias code='code .'
alias vim='nvim'
alias cursor='$APPS && ./cursor'
alias brave='brave .'
alias chrome='google-chrome .'
alias firefox='firefox .'
alias cursorapp='cd ~/Applications'
alias cursor='cursorapp && ./cursor'

alias voice='cd  /home/remcostoeten/dev/voice-to-clipboard && python voice2clipboard.py'
alias gocli='cd /home/remcostoeten/dev/bookmarks && ./run.sh'

alias v='voice'
alias c='cursor'
